title = "My Discombobulated Brain"
author = "My Discombobulated Brain"
description = "Compassionate mental health support, resources, and community for people and carers across the UK."
keywords = [ "mental health", "charity", "support", "wellness", "resources" ]
logo = "images/my-discombob-logo.svg"
favicon = "images/my-discombob-logo.svg"

[style_rules]
edges = "round"
expanded_nav = false
primary_color = "#007649"
secondary_color = "#be23b8"
title_font = "'Exo', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif"
body_font = "'Exo', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif"
stacked_button_position = "center"

[configs]
searchSummaryLength = 250
searchSummaryLengthMicro = 150
