#!/usr/bin/env python3
"""
generate_netlify_redirects.py
------------------------------
Scans the Hugo content/ directory for pages that declare a `redirect_from`
frontmatter key and writes a Netlify _redirects file that issues 301
permanent redirects from each legacy URL to the current canonical URL.

This preserves link equity and prevents 404s after URL changes.

Frontmatter example (YAML):
    ---
    title: My Updated Post
    redirect_from:
      - /old-url/
      - /really-old-url/
    ---

Usage:
    python3 scripts/generate_netlify_redirects.py

Output:
    static/_redirects   (committed to the repo; Netlify picks it up automatically)

The script is safe to re-run: it regenerates the file from scratch each time.
"""

import os
import re
import sys
from pathlib import Path

CONTENT_DIR = Path(__file__).parent.parent / "content"
OUTPUT_FILE = Path(__file__).parent.parent / "static" / "_redirects"

# Regex to extract YAML frontmatter block from a markdown file
FM_PATTERN = re.compile(r"^\s*---\s*\n(.*?)\n---\s*\n", re.DOTALL)

# Regex to extract `redirect_from` list from YAML frontmatter
REDIRECT_FROM_LIST = re.compile(
    r"^redirect_from\s*:\s*\n((?:[ \t]+-[^\n]+\n?)+)", re.MULTILINE
)
REDIRECT_FROM_SINGLE = re.compile(r"^redirect_from\s*:\s*([^\n\[]+)", re.MULTILINE)
REDIRECT_ITEM = re.compile(r"[ \t]+-[ \t]*['\"]?([^'\"\n]+)['\"]?")


def hugo_url_for_file(md_file: Path) -> str:
    """
    Derive the canonical Hugo URL for a content file, based on its path
    relative to content/.  This mirrors Hugo's default URL structure.

    Examples:
        content/blog/my-post/index.md  →  /blog/my-post/
        content/about.md               →  /about/
        content/_index.md              →  /
    """
    rel = md_file.relative_to(CONTENT_DIR)
    parts = list(rel.parts)

    # _index.md → section or home
    if parts[-1] == "_index.md":
        section = "/" + "/".join(parts[:-1])
        return section.rstrip("/") + "/" if section != "/" else "/"

    # index.md inside a directory (leaf bundle)
    if parts[-1] == "index.md":
        section = "/" + "/".join(parts[:-1])
        return section.rstrip("/") + "/"

    # Regular .md file
    slug = parts[-1].replace(".md", "")
    prefix = "/" + "/".join(parts[:-1]) if len(parts) > 1 else ""
    return f"{prefix}/{slug}/".replace("//", "/")


def parse_redirect_froms(frontmatter: str) -> list[str]:
    """Return the list of redirect_from URLs from parsed YAML frontmatter text."""
    # Try list form first
    match = REDIRECT_FROM_LIST.search(frontmatter)
    if match:
        block = match.group(1)
        return [m.group(1).strip() for m in REDIRECT_ITEM.finditer(block)]

    # Try scalar (single URL) form
    match = REDIRECT_FROM_SINGLE.search(frontmatter)
    if match:
        return [match.group(1).strip().strip("'\"")]

    return []


def collect_redirects() -> list[tuple[str, str]]:
    """Walk content/ and return (from_url, to_url) pairs."""
    redirects: list[tuple[str, str]] = []

    for md_file in sorted(CONTENT_DIR.rglob("*.md")):
        text = md_file.read_text(encoding="utf-8")
        fm_match = FM_PATTERN.match(text)
        if not fm_match:
            continue

        frontmatter = fm_match.group(1)
        from_urls = parse_redirect_froms(frontmatter)
        if not from_urls:
            continue

        canonical = hugo_url_for_file(md_file)
        for from_url in from_urls:
            # Ensure leading slash
            if not from_url.startswith("/"):
                from_url = "/" + from_url
            if from_url != canonical:
                redirects.append((from_url, canonical))

    return redirects


def write_redirects(redirects: list[tuple[str, str]]) -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Auto-generated by scripts/generate_netlify_redirects.py",
        "# Do not edit manually — re-run the script to update.",
        "# Format: <from>  <to>  <status>",
        "",
    ]
    for from_url, to_url in redirects:
        lines.append(f"{from_url}  {to_url}  301!")

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(redirects)} redirect(s) to {OUTPUT_FILE}")


if __name__ == "__main__":
    redirects = collect_redirects()
    if not redirects:
        print("No redirect_from entries found in content/. Nothing to write.")
        sys.exit(0)
    write_redirects(redirects)
